sudo: required
services:
  - docker

before_install:
  - docker build -t pimpuks/docker-react -f Dockerfile.dev . 

script:
  - docker run pimpuks/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react-ps"
  env: "DockerReactPs-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-458412413184"
  bucket_path: "docker-react-ps"
  on: 
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"